### check server status

GET http://localhost:8000/api/v1/

#   ===Admin API
### post new admin user

POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"Sandeep",
    "lName":"Prajapati",
    "email":"sandeepnewa@gmail.com",
    "password":"123456",
    "phone":"123456789",
    "address":"Bardia",
    "dob":"2020-02-20"
}

### login admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email":"sandeepnewa@gmail.com",
    "password":"123456"
}


#============== category APIS
# create new category
###
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"active",
    "name": "Macbook Pro M2",
    "parentId":"62fd8f939b5e7556f610263c"
}



### get categories 
GET http://localhost:8000/api/v1/category

{
    "status":"active",
    "name": "Macbook Pro M2",
    "parentId":""
}