### check server status

GET http://localhost:8000/api/v1/

#   ===Admin API
### post new admin user

POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"Sandeep",
    "lName":"Prajapati",
    "email":"sandeepnewa@gmail.com",
    "password":"123456",
    "phone":"123456789",
    "address":"Bardia",
    "dob":"2020-02-20"
}

### login admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email":"sandeepnewaa@gmail.com",
    "password":"123456"
}