### check server status
GET http://localhost:8000

# ======= Admin API
### post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"Prem",
    "lName": "Acharya",
    "email": "a@a3.com",
    "password": "123456",
    "phone": "123456789",
    "address": "sydney",
    "dob": ""
}

### login admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    
    "email": "a@a.com",
    "password": "123456"
  
}

### get new accessJWT
GET  http://localhost:8000/api/v1/admin-user/accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2NjEzODYzODIsImV4cCI6MTY2Mzk3ODM4Mn0.Ysy_hH67qTzn8SV_x_iW60oUZIFwG2CKRsa6CiwtxJI



### request otp for password reset
POST http://localhost:8000/api/v1/admin-user/request-password-reset-otp
Content-Type: application/json

{
"email": "a@a.com"
}

# ======== category apis

### create new category
POST  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status": "active",
    "name": "MacBook Laptops",
    "parentId": "62fd7a7da485fb1a10c4e278"
}


### get categories
GET http://localhost:8000/api/v1/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2NjEzMTU4MDUsImV4cCI6MTY2MTMxNjcwNX0.qfWc46Kfp-hlJ5SEbnaIKOiNWeJUfCB7i3n3EN24aMc


# ============ payment methods

###get payment methods
GET http://localhost:8000/api/v1/payment-method


###post payment methods
POST  http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "status": "inactive",
    "name": "Pay By PayId",
    "description" : "Follow the instruction to pay by PayId. AMEX is not supported"
}


### update payament methods     
PUT  http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "_id": "6306fc0f3d68613290aa4dc0",
    "status": "active",
    "name": "Pay By PAYID",
    "description" : "Follow the instruction to pay by PayId. "
}

### update payament methods     
DELETE   http://localhost:8000/api/v1/payment-method/6306fc0f3d68613290aa4dc0


# ========= product apis

### get products
GET http://localhost:8000/api/v1/product

### Post product
POST  http://localhost:8000/api/v1/product
Content-Type: application/json

{
 "name": "google book pro",
 "sku": "google-14",
 "description": "lorem lafjlsajfl lasdjflaslfas l jld lsajdlfjaajafj",
 "qty": 100,
 "price": 3000,
 "salesPrice": 0,
 "salesStartDate": null,
 "salesEndDate": null,
 "catId": "62fd7aaca485fb1a10c4e27a"

}


# =========== order Api

### get orders
GET http://localhost:8000/api/v1/order/11